name: kc_attendance
description: A KC College Attendance App
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.1.5
  device_info_plus: ^12.2.0
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  video_player: ^2.8.17
  firebase_core: ^3.11.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
